CREATE TABLE `exec_irc_bot`.`sn_comments` (
  `id` integer unsigned NOT NULL AUTO_INCREMENT,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` varchar(255) NOT NULL,
  `uid` varchar(255) NOT NULL,
  `score` varchar(255) NOT NULL,
  `score_num` varchar(255) NOT NULL,
  `subject` varchar(500) NOT NULL,
  `title` varchar(255) NOT NULL,
  `comment_body` varchar(3000) NOT NULL,
  `cid` varchar(255) NOT NULL,
  `sid` varchar(255) NOT NULL,
  `url` varchar(255) NOT NULL,
  `parent_cid` varchar(255) NOT NULL,
  `parent_url` varchar(500) NOT NULL,
  `story_url` varchar(500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `timestamp` (`timestamp` ASC),
  INDEX `user` (`user` ASC),
  INDEX `uid` (`uid` ASC),
  INDEX `score` (`score` ASC),
  INDEX `score_num` (`score_num` ASC),
  INDEX `subject` (`subject` ASC),
  INDEX `title` (`title` ASC),
  INDEX `comment_body` (`comment_body` ASC),
  INDEX `cid` (`cid` ASC),
  INDEX `sid` (`sid` ASC),
  INDEX `parent_cid` (`parent_cid` ASC)
) ENGINE=InnoDB AUTO_INCREMENT=1;
