<?php

#####################################################################################################

/*
exec:add ~submit-story
exec:edit ~submit-story timeout 60
exec:edit ~submit-story repeat 3600
exec:edit ~submit-story accounts_wildcard *
exec:edit ~submit-story servers irc.sylnt.us
exec:edit ~submit-story cmd php scripts/storybot_submit.php %%trailing%% %%dest%% %%nick%% %%alias%% %%cmd%%
exec:enable ~submit-story
*/

#####################################################################################################

date_default_timezone_set("UTC");

require_once("lib.php");
require_once("wiki_lib.php");

$trailing=trim($argv[1]);
$dest=$argv[2];
$nick=$argv[3];
$alias=$argv[4];
$cmd=$argv[5];

$allowed=array("crutchy","cmn32480","chromas","themightybuzzard","bytram");

$submit_host="dev.soylentnews.org";
#$submit_host="soylentnews.org";

$stories_path="/home/jared/git/storybot/Stories/";
$stories_path_filename=DATA_PATH."storybot_path.txt";

if (file_exists($stories_path_filename)==True)
{
  $stories_path_test=file_get_contents($stories_path_filename);
  if (($stories_path_test!==False) and (file_exists($stories_path_test)==True) and (is_dir($stories_path_test)==True))
  {
    $stories_path=rtrim($stories_path_test,"/")."/";
  }
}

$keep_days=3;

if (in_array(strtolower($nick),$allowed)==True)
{
  if ($trailing=="list")
  {
    refresh_list();
    privmsg("http://wiki.soylentnews.org/wiki/Storybot");
    return;
  }
  if ($cmd<>"INTERNAL")
  {
    submit_story($trailing);
    return;
  }
}

delete_old();
refresh_list();

#####################################################################################################

function refresh_list()
{
  global $stories_path;
  $file_list=scandir($stories_path);
  $text="<p>TO SUBMIT ONE OF THESE STORIES, TYPE \"~submit-story #\" IN SOYLENTNEWS IRC, WHERE # IS THE ID FROM THE LIST BELOW.</p>".PHP_EOL;
  $text=$text."{| class=\"wikitable\"".PHP_EOL;
  $text=$text."|-".PHP_EOL;
  $text=$text."! link !! id !! title".PHP_EOL;
  for ($i=0;$i<count($file_list);$i++)
  {
    $filename=$file_list[$i];
    if (($filename==".") or ($filename==".."))
    {
      continue;
    }
    $fn=$stories_path.$filename;
    $content=file_get_contents($fn);
    if ($content===False)
    {
      continue;
    }
    $url=extract_text($content,"Original URL: <a href='","'>");
    $title=extract_text($content,"<p>Title: ","</p>");
    if (($url===False) or ($title===False))
    {
      continue;
    }
    $title=clean_title($title);
    $id=substr(md5($url),0,5);
    $text=$text."|-".PHP_EOL;
    $text=$text."| [$url link] || $id || $title".PHP_EOL;
  }
  $text=$text."|}".PHP_EOL;
  $text=$text."<p>autogenerated by [[IRC:exec|exec]] irc bot. don't manually edit this page</p>".PHP_EOL;
  $title="Storybot";
  $app_id="storybot";
  if (internal_login($app_id)==False)
  {
    return;
  }
  internal_rewrite_page($app_id,$title,$text);
  internal_logout($app_id);
}

#####################################################################################################

function delete_old()
{
  global $stories_path;
  global $keep_days;
  $file_list=scandir($stories_path);
  $datum=time();
  for ($i=0;$i<count($file_list);$i++)
  {
    $filename=$stories_path.$file_list[$i];
    $t=filemtime($filename);
    if (($datum-$t)>($keep_days*24*60*60))
    {
      if (@unlink($filename)===False)
      {
        term_echo("storybot: ERROR DELETING OLD FILE \"".$filename."\"");
      }
      else
      {
        term_echo("storybot: deleted old file \"".$filename."\"");
      }
    }
  }
}

#####################################################################################################

function clean_title($title)
{
  $title=str_replace("_"," ",$title);
  $i=strpos($title,"--");
  if ($i!==False)
  {
    $title=trim(substr($title,0,$i));
  }
  $i=strpos($title,"|");
  if ($i!==False)
  {
    $title=trim(substr($title,0,$i));
  }
  $i=strpos($title," - ");
  if ($i!==False)
  {
    $title=trim(substr($title,0,$i));
  }
  $i=strpos($title," : ");
  if ($i!==False)
  {
    $title=trim(substr($title,0,$i));
  }
  $i=strpos($title," — ");
  if ($i!==False)
  {
    $title=trim(substr($title,0,$i));
  }
  $i=strpos($title," • ");
  if ($i!==False)
  {
    $title=trim(substr($title,0,$i));
  }
  return $title;
}

#####################################################################################################

function submit_story($id)
{
  global $stories_path;
  global $submit_host;
  $file_list=scandir($stories_path);
  $story_filename="";
  for ($i=0;$i<count($file_list);$i++)
  {
    $filename=$file_list[$i];
    if (($filename==".") or ($filename==".."))
    {
      continue;
    }
    $fn=$stories_path.$filename;
    $content=file_get_contents($fn);
    if ($content===False)
    {
      continue;
    }
    $test_url=extract_text($content,"Original URL: <a href='","'>");
    if ($test_url===False)
    {
      continue;
    }
    $test_id=substr(md5($test_url),0,5);
    if ($test_id===$id)
    {
      $story_filename=$fn;
      break;
    }
  }
  if (file_exists($story_filename)==False)
  {
    privmsg("file \"$story_filename\" not found");
    return;
  }
  $data=file_get_contents($story_filename);
  if ($data===False)
  {
    term_echo("error reading file \"$story_filename\"");
    return;
  }
  $source_title=extract_text($data,"<p>Title: ","</p>");
  $source_title=clean_title($source_title);
  privmsg("attempting to submit story: \"$source_title\"");
  $port=443;
  $uri="/submit.pl";
  $response=wget($submit_host,$uri,$port,ICEWEASEL_UA);
  $html=strip_headers($response);
  $reskey=extract_text($html,"<input type=\"hidden\" id=\"reskey\" name=\"reskey\" value=\"","\">");
  if ($reskey===False)
  {
    privmsg("error: unable to extract reskey");
    return;
  }
  sleep(25);
  $params=array();
  $params["reskey"]=$reskey;
  $params["name"]=get_bot_nick();
  $params["email"]="";
  $params["subj"]=trim(substr($source_title,0,100));
  $params["primaryskid"]="1";
  $params["tid"]="6";
  $params["sub_type"]="plain";
  $params["story"]=$data."\n\n-- submitted from IRC";
  $params["op"]="SubmitStory";
  $response=wpost($submit_host,$uri,$port,ICEWEASEL_UA,$params);
  $html=strip_headers($response);
  strip_all_tag($html,"head");
  strip_all_tag($html,"script");
  strip_all_tag($html,"style");
  strip_all_tag($html,"a");
  $html=strip_tags($html);
  $html=clean_text($html);
  var_dump($html);
  if (strpos($html,"Perhaps you would like to enter an email address or a URL next time.")!==False)
  {
    privmsg("submission successful - https://$submit_host/submit.pl?op=list");
  }
  else
  {
    privmsg("error: something went wrong with your submission");
    return;
  }
  unlink($story_filename);
  refresh_list();
}

#####################################################################################################

?>
